### ISSUE TITLE
bearerApiKey don't wokrs

### ISSUE THREAD

**Issue by villander** [dschmidt/ember-cli-deploy-sentry#58]
I'm using bearerApiKey, but i have this error

STAGING_SENTRY_API_KEY=Bearer d649f01f5f1746099cedc74f385833
****999

```
|
+- didFail
Error: no auth mechanism defined
Error: no auth mechanism defined
    at Auth.onRequest (/Users/villander/Projects/web_app/node_modules/request/lib/auth.js:133:32)
    at Request.auth (/Users/villander/Projects/web_app/node_modules/request/request.js:1270:14)
    at Request.init (/Users/villander/Projects/web_app/node_modules/request/request.js:379:10)
    at Request.RP$initInterceptor [as init] (/Users/villander/Projects/web_app/node_modules/ember-cli-deploy-sentry/node_modules/request-promise/lib/rp.js:123:25)
    at new Request (/Users/villander/Projects/web_app/node_modules/request/request.js:128:8)
    at request (/Users/villander/Projects/web_app/node_modules/request/index.js:54:10)
    at Class.doesReleaseExist (/Users/villander/Projects/web_app/node_modules/ember-cli-deploy-sentry/index.js:103:16)
    at Class.didPrepare (/Users/villander/Projects/web_app/node_modules/ember-cli-deploy-sentry/index.js:88:21)
    at Object.fn (/Users/villander/Projects/web_app/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/Users/villander/Projects/web_app/node_modules/ember-cli-deploy/lib/models/pipeline.js:173:19)
    at tryCatch (/Users/villander/Projects/web_app/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/villander/Projects/web_app/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/villander/Projects/web_app/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/villander/Projects/web_app/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
|
Pipeline aborted
➜  web_app git:(feature/sentry) ✗ 
```

I created a API KEY on sentry api but this don't work as well

https://docs.sentry.io/api/projects/post-project-keys/

```
{
    "dateCreated": "2018-11-27T16:49:27.377Z",
    "id": "645bf3f548ce46ca8c8459f54a66480f",
    "browserSdk": {
        "choices": [
            [
                "latest",
                "latest"
            ],
            [
                "4.x",
                "4.x"
            ]
        ]
    },
    "name": "Sharing Quagga",
    "projectId": 1328216,
    "rateLimit": null,
    "label": "Sharing Quagga",
    "dsn": {
        "cdn": "https://js.sentry-cdn.com/645bf3f548ce46ca8c8459f54a66480f.min.js",
        "minidump": "https://sentry.io/api/1328216/minidump/?sentry_key=645bf3f548ce46ca8c8459f54a66480f",
        "csp": "https://sentry.io/api/1328216/csp-report/?sentry_key=645bf3f548ce46ca8c8459f54a66480f",
        "secret": "https://645bf3f548ce46ca8c8459f54a66480f:802fd6e3e8ed4bb18a1728a2c9b0fab6@sentry.io/1328216",
        "unreal": "https://sentry.io/api/1328216/unreal/645bf3f548ce46ca8c8459f54a66480f/",
        "security": "https://sentry.io/api/1328216/security/?sentry_key=645bf3f548ce46ca8c8459f54a66480f",
        "public": "https://645bf3f548ce46ca8c8459f54a66480f@sentry.io/1328216"
    },
    "browserSdkVersion": "4.x",
    "secret": "802fd6e3e8ed4bb18a1728a2c9b0fab6",
    "isActive": true,
    "public": "645bf3f548ce46ca8c8459f54a66480f"
}
```

```

**Comment by villander** [comment]
@Turbo87 what about?

**Comment by Turbo87** [comment]
idk, I'm not maintaining or using this addon

**Comment by dschmidt** [comment]
Isn't that one deprecated and you should use the bearer token setting?

**Comment by villander** [comment]
@dschmidt I tried use this token, but the error continue

![image](https://user-images.githubusercontent.com/10222774/49410648-835e3600-f71a-11e8-88df-3ad279662f96.png)

```
STAGING_SENTRY_SITE_URL=https://qa-my.example.com
STAGING_SENTRY_ORGANIZATION_SLUG=villander
STAGING_SENTRY_PROJECT_SLUG=javascript
STAGING_SENTRY_API_KEY=7f4710acedf411e8b0514201c0a8d032
SENTRY_BASE_URL=https://sentry.io/
```

**Comment by villander** [comment]
my bad
